name: Archive

on:
  workflow_dispatch:

concurrency:
  group: "archive"
  cancel-in-progress: false

jobs:
  forumPosts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout scraper
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout forumPosts archive
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: deeeepio-archive/forumPosts
          path: forumPosts

      - name: Run script
        run: |
          npm run scrape:forumPosts

      - name: Save changes to scraper repo
        run: |
          git add .
          git commit -m "Update forumPosts progress"
          git rebase
          git push

      - name: Save changes to forumPosts archive
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update forumPosts archive
          repository: forumPosts

  maps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout scraper
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout maps archive
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: deeeepio-archive/maps
          path: maps

      - name: Run script
        run: |
          npm run scrape:maps

      - name: Save changes to scraper repo
        run: |
          git add .
          git commit -m "Update maps progress"
          git rebase
          git push

      - name: Save changes to maps archive
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update maps archive
          repository: maps

  users:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout scraper
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout users archive
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: deeeepio-archive/users
          path: users

      - name: Run script
        run: |
          npm run scrape:users

      - name: Save changes to scraper repo
        run: |
          git add .
          git commit -m "Update users progress"
          git rebase
          git push

      - name: Save changes to users archive
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update users archive
          repository: users
