name: Archive

on:
  workflow_dispatch:

concurrency:
  group: "archive"
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout scraper
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout forumPosts archive
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: deeeepio-archive/forumPosts
          path: forumPosts

      - name: Run forumPosts archive script
        run: |
          npm run scrape:forumPosts

      - name: Checkout maps archive
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: deeeepio-archive/maps
          path: maps

      - name: Run maps archive script
        run: |
          npm run scrape:maps

      - name: Checkout users archive
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: deeeepio-archive/users
          path: users

      - name: Run users archive script
        run: |
          npm run scrape:users

      - name: Save changes to scraper repo
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit --author="${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>" -m "Update progress"
          git rebase
          git push

      - name: Save changes to forumPosts archive
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update forumPosts archive
          repository: forumPosts

      - name: Save changes to maps archive
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update maps archive
          repository: maps

      - name: Save changes to users archive
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update users archive
          repository: users
